[package]
name = "nexpingdesk-config"
description = "Nexpingdesk configuration schema and storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nexpingdesk-layout.workspace = true
nexpingdesk-proto.workspace = true
directories.workspace = true
getrandom.workspace = true
serde.workspace = true
thiserror.workspace = true
time.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
